site_name: "Computer-Oriented Geoscience Lab"
site_description: "Geophysical research powered by open-source software"
brand: "images/compgeolab-banner.svg"
favicon: "images/favicon.png"
url: "https://www.compgeolab.org"
repository: compgeolab/website
author: Leonardo Uieda
mastodon: leouieda
mastodon_server: scicomm.xyz
github: compgeolab
linkedin: uieda
orcid: 0000-0001-6123-9515
location:
  department: Departmento de Geofísica
  school: Instituto de Astronomia, Geofísica e Ciências Atmosféricas
  university: Universidade de São Paulo
  country: Brasil
language: en
keywords: 'science, geoscience, geophysics, software, open-source'
navigation:
  - name: Home
    id: index
  - name: Team
    id: team/index
  - name: Research
    id: research/index
  - name: Software
    id: software/index
  - name: Data
    id: data/index
  - name: News
    id: news/index
  - name: Manual
    id: manual/index
ignore:
  - README.md
  - LICENSE.md
  - CONTRIBUTING.md
  - environment.yml
  - Makefile
  - css/academicons/README.md
