site_name: "GR-Water project"
site_description: "Multiscale earth critical zone monitoring for post-fire forest ecosystem management"
brand: "images/Logo - Tech4Agro_primary.png"
favicon: "images/Logo - Tech4Agro_primary.png"
thumbnail: "images/Logo - Tech4Agro_primary.png"
#url: "https://www.compgeolab.org"
#domain: compgeolab.org
#repository: compgeolab/website
#repository_branch: main
author: Benjamin Mary
#mastodon: leouieda
#mastodon_server: bertha.social
github: website_grwater
#linkedin: uieda
#researchgate: https://www.researchgate.net/lab/Computer-Oriented-Geoscience-Lab-Leonardo-Uieda
location:
  department: Tech4Agro
  school: ICA
  university: Consejo Superior de Investigaciones Cient√≠ficas,Spanish National Research Council,CSIC
  country: Spain
language: en
keywords: 'science, geoscience, geophysics, evapotranspiration, fires, software, open-source'
navigation:
  - name: Home
    id: index
  - name: News
    id: news/index
  - name: Team
    id: team/index
  - name: Research
    id: research/index
  #- name: Manual
  #  id: manual/index
ignore:
  - README.md
  - LICENSE.md
  - CONTRIBUTING.md
  - environment.yml
  - Makefile
  - css/academicons/README.md
  

